"""Builds the SYNTHETIC / DEMO seed files in data/.

Outputs (all clearly labelled synthetic):
  data/support_categories.csv   guided support categories (Internet, Mobile, ...)
  data/products.csv             product catalogue + detection keywords
  data/intent_taxonomy.csv      30 intents, keywords, examples, clarifying questions
  data/knowledge_base.csv       42 knowledge articles (41 ACTIVE incl. 5 general, 1 DRAFT)
  data/candidate_cases.csv      12 authored unseen-issue candidate cases
  data/eval_unknown_complaints.csv  out-of-taxonomy complaints for unknown-detection eval
  data/tickets.csv              demo ticket set = stratified sample of the 60K dataset
                                + hand-authored demo tickets (same schema)

Usage:  python scripts/build_seed_data.py [--dataset data/telecom_support_adaptive_60000.csv]
"""
from __future__ import annotations

import argparse
import csv
import json
import random
from pathlib import Path

from seed_customer_steps import CUSTOMER_STEPS

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

SYNTHETIC_NOTE = "SYNTHETIC / DEMO DATA - not real telecom operator data."

SUPPORT_CATEGORIES = [
    # name, parent, icon, description
    ("Internet", "", "globe", "Home internet access, outages, activation and installation"),
    ("Broadband", "Internet", "router", "Fixed broadband speed and stability"),
    ("Wi-Fi", "Internet", "wifi", "Home Wi-Fi and router behaviour"),
    ("Mobile", "", "phone", "Mobile data and network signal"),
    ("5G", "Mobile", "bolt", "5G availability and network mode"),
    ("Calls", "", "call", "Voice call drops and quality"),
    ("SMS", "", "message", "Text messages and one-time passwords"),
    ("SIM", "", "sim", "SIM / eSIM detection, activation and replacement"),
    ("Billing", "", "receipt", "Bills, charges, payments and refunds"),
    ("Recharge", "", "wallet", "Recharges, top-ups and plans"),
    ("Account", "", "user", "Login, password, profile and account security"),
    ("Roaming", "", "plane", "Service while travelling abroad"),
]

PRODUCTS = [
    # name, support_category, keywords
    ("broadband", "Broadband", ["broadband", "fibre", "fiber", "home internet", "internet connection", "internet"]),
    ("router", "Wi-Fi", ["router", "modem"]),
    ("ONT", "Broadband", ["ont", "optical terminal", "fibre box"]),
    ("Wi-Fi", "Wi-Fi", ["wifi", "wireless network"]),
    ("mobile data", "Mobile", ["mobile data", "mobile internet", "data connection", "4g", "lte", "cellular data", "data"]),
    ("mobile network", "Mobile", ["signal", "network coverage", "coverage", "network"]),
    ("5G service", "5G", ["5g"]),
    ("voice service", "Calls", ["call", "calls", "calling", "voice call"]),
    ("SMS service", "SMS", ["sms", "text message", "text messages", "otp"]),
    ("SIM", "SIM", ["sim", "sim card"]),
    ("eSIM", "SIM", ["esim", "e sim"]),
    ("mobile bill", "Billing", ["bill", "invoice", "charge", "charged", "billing"]),
    ("payment", "Billing", ["payment", "card declined", "transaction"]),
    ("refund", "Billing", ["refund"]),
    ("recharge plan", "Recharge", ["recharge", "top up", "topup", "balance"]),
    ("mobile plan", "Recharge", ["plan", "plans", "package", "tariff"]),
    ("customer account", "Account", ["account", "login", "log in", "password", "profile"]),
    ("roaming", "Roaming", ["roaming", "abroad", "international"]),
]

# name, display, domain_category, support_category, default_product, keywords, examples, clarifying question, description
INTENTS = [
    ("broadband_disconnects", "Broadband Disconnect", "CONNECTIVITY", "Broadband", "broadband",
     ["broadband keeps disconnecting", "keeps disconnecting", "disconnecting", "disconnects", "broadband drops", "internet drops",
      "connection drops", "drops every", "cutting out", "drops out", "dropping out", "connection keeps dropping"],
     ["My broadband keeps disconnecting every evening", "The internet connection drops out several times a day",
      "My fibre connection keeps cutting out"],
     "At what time of day do the drops happen, and does the router or ONT show any warning light?",
     "Fixed broadband connection drops intermittently"),
    ("broadband_no_internet", "Broadband No Internet", "CONNECTIVITY", "Internet", "broadband",
     ["no internet", "connected but no internet", "internet not working", "broadband not working", "internet down",
      "no internet access", "broadband down"],
     ["My broadband is connected to the router but there is no internet", "Home internet is completely down"],
     "Are the router and ONT lights normal, and is the problem on every device?",
     "Router is connected but there is no internet access"),
    ("broadband_slow", "Broadband Slow", "CONNECTIVITY", "Broadband", "broadband",
     ["broadband slow", "broadband speed", "slow broadband", "slow internet", "internet slow", "speed slow", "buffering",
      "low speed", "slow speeds"],
     ["My broadband speed is slow during the evening", "Internet is very slow and videos keep buffering"],
     "When does it happen, and is it slow on both Wi-Fi and wired devices?",
     "Fixed broadband performance is slower than expected"),
    ("wifi_not_working", "Wi-Fi Not Working", "CONNECTIVITY", "Wi-Fi", "Wi-Fi",
     ["wifi not working", "wifi down", "wifi stopped", "cannot connect wifi", "wifi not connecting", "wifi network not showing",
      "wifi signal weak", "wifi keeps disconnecting"],
     ["Wi-Fi is not working on my devices", "My phone cannot connect to the home Wi-Fi"],
     "Does the problem affect every device, or only one?",
     "Home Wi-Fi unavailable or failing on devices"),
    ("router_restart_issue", "Router Restart Issue", "CONNECTIVITY", "Wi-Fi", "router",
     ["restarted router but", "router keeps restarting", "router restart issue", "router not restarting", "router reboot loop",
      "restart did not fix", "connection problem remains"],
     ["I restarted the router but the connection problem remains", "My router keeps rebooting by itself"],
     "Which lights does the router show after the restart completes?",
     "Problem persists after a router restart, or router restarts unexpectedly"),
    ("mobile_data_not_working", "Mobile Data Not Working", "CONNECTIVITY", "Mobile", "mobile data",
     ["mobile data not working", "mobile data", "data not working", "mobile internet not working", "mobile internet",
      "cellular data", "4g not working", "data connection not working"],
     ["My mobile data is not working", "Mobile internet stopped working on my phone"],
     "Do you see network bars and the mobile data icon on the phone?",
     "Mobile data connection unavailable"),
    ("mobile_data_slow", "Mobile Data Slow", "CONNECTIVITY", "Mobile", "mobile data",
     ["mobile data slow", "data slow", "slow data", "mobile internet slow", "data speed slow", "4g slow"],
     ["My mobile data is very slow", "4G speed has become extremely slow"],
     "Does the slowdown happen in one location or everywhere?",
     "Mobile data performance is slow"),
    ("no_signal", "No Network Signal", "CONNECTIVITY", "Mobile", "mobile network",
     ["no signal", "no network", "no network signal", "no service", "network not available", "emergency calls only",
      "sos only", "signal bars"],
     ["My phone shows no network signal", "Phone says no service at home"],
     "Is the no-signal problem in one location, and has the SIM been reseated?",
     "Device has no mobile network signal"),
    ("5g_not_available", "5G Not Available", "CONNECTIVITY", "5G", "5G service",
     ["5g not available", "5g not showing", "no 5g", "5g not working", "5g icon", "5g missing", "only 4g"],
     ["My phone supports 5G but 5G is not available", "The 5G icon never appears on my phone"],
     "Which network mode is selected on the device?",
     "5G is not available on a 5G-capable device"),
    ("call_drops", "Call Drops", "CONNECTIVITY", "Calls", "voice service",
     ["calls keep dropping", "call drops", "calls drop", "dropped calls", "call dropping", "calls get cut", "call disconnects",
      "calls cut off"],
     ["My calls keep dropping", "Calls get cut after a minute"],
     "Do the calls drop in a specific location or at a specific time?",
     "Voice calls disconnect unexpectedly"),
    ("call_quality", "Call Quality", "CONNECTIVITY", "Calls", "voice service",
     ["cannot hear", "hear me clearly", "call quality", "echo", "voice breaking", "robotic voice", "choppy calls", "crackling"],
     ["People cannot hear me clearly during calls", "There is an echo on every call"],
     "Does it affect incoming calls, outgoing calls, or both?",
     "Poor voice quality on calls"),
    ("sms_not_received", "SMS Not Received", "CONNECTIVITY", "SMS", "SMS service",
     ["not receiving sms", "sms not received", "not getting sms", "otp not received", "messages not arriving",
      "text messages not", "not receiving otp"],
     ["I am not receiving SMS messages", "OTP messages never arrive on my phone"],
     "Is it incoming SMS, outgoing SMS, or both?",
     "SMS or OTP messages not delivered"),
    ("sim_not_detected", "SIM Not Detected", "SIM", "SIM", "SIM",
     ["sim not detected", "no sim", "sim not recognized", "detect sim", "sim unavailable", "invalid sim", "insert sim",
      "sim card not detected"],
     ["My phone does not detect the SIM", "Phone says no SIM card inserted"],
     "Has the SIM been tested in another phone?",
     "Device does not detect the SIM card"),
    ("sim_activation", "SIM Activation", "SIM", "SIM", "SIM",
     ["sim not activated", "activate sim", "sim activation", "new sim not working", "sim not active", "activate new sim"],
     ["My new SIM has not activated", "I need to activate my new SIM card"],
     "When was the SIM inserted, and was the activation request submitted?",
     "New SIM not yet active"),
    ("sim_replacement", "SIM Replacement", "SIM", "SIM", "eSIM",
     ["replacement sim", "replace sim", "lost sim", "damaged sim", "sim replacement", "esim transfer", "new esim",
      "broken sim"],
     ["I need a replacement SIM", "My SIM card is damaged and needs replacing"],
     "Is the replacement for a lost, damaged, or changed device?",
     "Customer needs a replacement SIM or eSIM"),
    ("roaming_not_working", "Roaming Not Working", "CONNECTIVITY", "Roaming", "roaming",
     ["roaming not working", "roaming", "abroad", "travelling", "international roaming", "overseas"],
     ["My roaming service is not working", "My phone has no service while abroad"],
     "Which country are you in, and is roaming enabled on the line?",
     "Service unavailable while roaming"),
    ("billing_dispute", "Billing Dispute", "BILLING", "Billing", "mobile bill",
     ["dispute", "charged twice", "double charged", "overcharged", "wrong bill", "bill incorrect", "incorrect bill",
      "billing error", "invoice wrong", "bill", "invoice", "charged"],
     ["I want to dispute a charge on my bill", "I was charged twice this month"],
     "Which billing period and line item is being disputed?",
     "Customer disputes a bill amount"),
    ("unexpected_charge", "Unexpected Charge", "BILLING", "Billing", "mobile bill",
     ["unexpected charge", "unknown charge", "extra charge", "unrecognized charge", "hidden charge", "charge on my bill",
      "charge do not recognize"],
     ["There is an unexpected charge on my bill", "I see an extra charge I do not recognise"],
     "What is the name of the line item and which billing period is it on?",
     "Unrecognised charge appears on the bill"),
    ("payment_failed", "Payment Failed", "BILLING", "Billing", "payment",
     ["payment failed", "payment declined", "payment not going through", "could not pay", "payment unsuccessful",
      "transaction failed", "card declined", "bill payment failed"],
     ["My bill payment failed", "My card payment keeps getting declined"],
     "Was money deducted from the account even though the payment failed?",
     "Bill payment unsuccessful"),
    ("refund_status", "Refund Status", "BILLING", "Billing", "refund",
     ["refund", "refund status", "money back", "refund not received", "where is my refund"],
     ["I want to know the status of my refund", "My refund has not arrived"],
     "Do you have the refund reference or the original transaction date?",
     "Customer asks about a refund"),
    ("recharge_issue", "Recharge Issue", "PLAN", "Recharge", "recharge plan",
     ["recharge", "top up", "topup", "recharge failed", "recharge not credited", "balance not updated", "recharge did not complete"],
     ["My recharge did not complete", "I topped up but the balance did not update"],
     "Do you have the recharge transaction reference?",
     "Recharge or top-up not applied"),
    ("plan_change", "Plan Change", "PLAN", "Recharge", "mobile plan",
     ["change plan", "change my plan", "upgrade plan", "downgrade", "switch plan", "plan change", "change current plan"],
     ["I want to change my current plan", "Please upgrade my plan"],
     "Which plan would you like to move to?",
     "Customer wants to change plan"),
    ("plan_information", "Plan Information", "PLAN", "Recharge", "mobile plan",
     ["available plans", "plan information", "plan details", "which plan", "plan options", "information about plans",
      "compare plans"],
     ["I want information about available plans", "What plans can I choose from?"],
     "Are you interested in mobile or broadband plans?",
     "Customer requests plan information"),
    ("account_login", "Account Login", "ACCOUNT", "Account", "customer account",
     ["cannot log in", "cannot login", "login failed", "log in", "login", "sign in", "locked out"],
     ["I cannot log in to my account", "The app says my login failed"],
     "What message do you see when the login fails?",
     "Customer cannot sign in to the self-care account"),
    ("account_security", "Account Security", "SECURITY", "Account", "customer account",
     ["hacked", "unauthorized", "unauthorised", "suspicious", "security of my account", "fraud", "someone accessed",
      "sim swap", "account security", "phishing"],
     ["I am concerned about the security of my account", "Someone accessed my account without permission"],
     "When did you first notice the suspicious activity?",
     "Possible compromise or suspicious account activity"),
    ("password_reset", "Password Reset", "ACCOUNT", "Account", "customer account",
     ["reset password", "forgot password", "password reset", "change password", "reset account password"],
     ["I need to reset my account password", "I forgot my password"],
     "Can you receive the verification code on your registered contact?",
     "Customer needs a password reset"),
    ("profile_update", "Profile Update", "ACCOUNT", "Account", "customer account",
     ["update profile", "update account profile", "change address", "update email", "change email", "update phone number",
      "profile update", "update my details"],
     ["I need to update my account profile", "I want to change the email on my account"],
     "Which profile field needs to change?",
     "Customer wants to update profile details"),
    ("service_activation", "Service Activation", "INSTALLATION", "Internet", "broadband",
     ["service not activated", "service has not activated", "activation pending", "activate service", "service activation",
      "service not active"],
     ["My service has not activated yet", "Activation is still pending"],
     "Do you have the activation request reference?",
     "Service activation pending or incomplete"),
    ("new_connection_status", "New Connection Status", "INSTALLATION", "Internet", "broadband",
     ["new connection", "installation status", "new broadband connection", "connection status", "installation",
      "installation date"],
     ["I want to check the status of my new broadband connection", "When will my installation happen?"],
     "Do you have the new-connection request reference?",
     "Status of a new connection or installation"),
    ("service_outage", "Service Outage", "SERVICE", "Internet", "broadband",
     ["outage", "service outage", "area outage", "network down in my area", "everyone in my area", "whole area",
      "neighbours also"],
     ["I think there may be a service outage in my area", "The whole street has no internet"],
     "Which area or postcode is affected?",
     "Possible area-wide service outage"),
]

# Knowledge base: article_id -> (intent, title, product, symptoms, steps, escalate_when, caution)
KB = {
    "KB-002": ("mobile_data_slow", "Slow mobile data: standard checks", "mobile data",
               "Mobile data works but pages and apps load slowly.",
               ["Check signal availability and whether the slowdown occurs consistently or only in certain places.",
                "Restart the device and retry the connection.",
                "Collect time and location details if the slowdown continues."],
               "The slowdown continues across locations after a device restart.",
               "Do not quote or promise specific speeds."),
    "KB-003": ("call_drops", "Dropped calls: signal and device checks", "voice service",
               "Voice calls disconnect unexpectedly during the conversation.",
               ["Check signal availability where the calls drop.",
                "Retry calls from another location if possible.",
                "Restart the device.",
                "Record the time and frequency of dropped calls for escalation if the issue continues."],
               "Calls keep dropping after the device restart and in more than one location.",
               "Do not attribute drops to a network fault unless a confirmed outage exists."),
    "KB-004": ("call_quality", "Poor call quality: triage", "voice service",
               "Callers cannot hear clearly, or audio is choppy or echoing.",
               ["Check signal availability during the affected calls.",
                "Retry the call to confirm the problem repeats.",
                "Restart the device.",
                "Record whether incoming, outgoing, or both call directions are affected."],
               "Quality problems persist on calls in both directions after a restart.",
               "Do not ask the customer to change device hardware settings that are not listed here."),
    "KB-005": ("no_signal", "No network signal on the device", "mobile network",
               "The phone shows no signal, no service, or emergency calls only.",
               ["Restart the device.",
                "Confirm the SIM is seated correctly.",
                "Check whether network service returns after the restart.",
                "Escalate with location and device details if no signal persists."],
               "No signal persists after restart and SIM reseat.",
               "Do not confirm a mast or area outage unless it is listed in the approved service-status source."),
    "KB-006": ("sms_not_received", "SMS or OTP messages not received", "SMS service",
               "Text messages or one-time passwords are not arriving.",
               ["Restart the device.",
                "Verify that network service is available.",
                "Send a test message.",
                "Record whether incoming or outgoing SMS is affected."],
               "Messages still fail after restart while network service is available.",
               "Never ask the customer to share an OTP with the agent."),
    "KB-007": ("roaming_not_working", "Roaming service not working", "roaming",
               "No service or no data while travelling abroad.",
               ["Confirm roaming is enabled for the service.",
                "Restart the device.",
                "Retry network registration.",
                "Escalate with the roaming location and service details if unsuccessful."],
               "Roaming remains unavailable after registration is retried.",
               "Do not quote roaming prices; refer to the approved tariff information."),
    "KB-008": ("5g_not_available", "5G not available on a capable device", "5G service",
               "Device supports 5G but only connects to 4G or lower.",
               ["Confirm that the device and the service support 5G.",
                "Check the selected network mode on the device.",
                "Restart the device.",
                "Record the observed network mode if 5G remains unavailable."],
               "5G remains unavailable with the correct network mode selected.",
               "Do not promise 5G coverage at a specific address."),
    "KB-009": ("broadband_slow", "Slow broadband: diagnostic steps", "broadband",
               "Broadband connects but speed is slower than expected.",
               ["Restart the router/ONT.",
                "Test the connection again.",
                "Compare performance across devices where possible.",
                "Record the time pattern and connection details if the slowdown persists."],
               "Slow speeds persist across devices after a restart.",
               "Do not promise a specific speed."),
    "KB-010": ("broadband_disconnects", "Broadband disconnects intermittently", "broadband",
               "Fixed broadband connection drops and reconnects intermittently.",
               ["Check router/ONT status indicators.",
                "Restart the equipment.",
                "Observe whether the connection drops again.",
                "Record the time pattern of the drops for escalation if intermittent drops continue."],
               "Intermittent drops continue after the equipment restart.",
               "Do not attribute drops to the customer's equipment without status evidence."),
    "KB-012": ("wifi_not_working", "Home Wi-Fi not working", "Wi-Fi",
               "Devices cannot connect to, or lose, the home Wi-Fi network.",
               ["Check that Wi-Fi is enabled on the affected device.",
                "Restart the router.",
                "Retry from another device if available.",
                "Record whether the issue affects all devices."],
               "No device can connect after the router restart.",
               "Do not ask the customer to share their Wi-Fi password in chat."),
    "KB-013": ("router_restart_issue", "Problem remains after router restart", "router",
               "The customer restarted the router but the connection problem remains.",
               ["Confirm the router/ONT completed its restart.",
                "Check connection status and physical links.",
                "Retry the service.",
                "Escalate with the status indicators if the issue remains."],
               "The issue remains after a completed restart with physical links confirmed.",
               "Do not recommend a factory reset; it is not part of this procedure."),
    "KB-014": ("new_connection_status", "New connection status enquiry", "broadband",
               "Customer asks when a new connection or installation will be completed.",
               ["Verify the request reference.",
                "Check the installation status through the approved support process.",
                "Route the request for agent follow-up if the status cannot be confirmed."],
               "The installation status cannot be confirmed.",
               "Do not commit to an installation date that is not shown in the approved status."),
    "KB-015": ("service_activation", "Service not yet activated", "broadband",
               "A purchased service has not become active.",
               ["Verify the activation request status.",
                "Confirm the required activation step has completed.",
                "Route the case for agent follow-up if the service remains inactive."],
               "The service remains inactive after the activation step is confirmed.",
               "Do not promise an activation time."),
    "KB-016": ("account_login", "Cannot log in to the self-care account", "customer account",
               "The customer cannot sign in to the online account or app.",
               ["Verify the entered account identifier.",
                "Retry login.",
                "Use the approved account recovery process if access remains unavailable."],
               "Access remains unavailable after the recovery process.",
               "Never ask the customer for their password."),
    "KB-017": ("password_reset", "Password reset", "customer account",
               "The customer needs to reset a forgotten password.",
               ["Use the approved password-reset flow.",
                "Complete the verification step.",
                "Escalate through account support if recovery cannot be completed."],
               "The verification step cannot be completed.",
               "Never ask the customer to read out a verification code."),
    "KB-018": ("profile_update", "Updating account profile details", "customer account",
               "The customer wants to change profile information such as email or address.",
               ["Use the approved account-profile update flow.",
                "Verify the saved details.",
                "Route the request to an agent if the required field cannot be changed."],
               "The required field cannot be changed through the flow.",
               "Do not change identity details without the approved verification."),
    "KB-019": ("billing_dispute", "Raising a billing dispute", "mobile bill",
               "The customer disagrees with an amount on the bill.",
               ["Review the bill details.",
                "Identify the disputed line item.",
                "Record the billing period and the reason for the dispute.",
                "Submit the dispute through the approved billing process."],
               "The dispute cannot be resolved by reviewing the bill details.",
               "Do not promise a refund or credit amount; outcomes depend on the billing review."),
    "KB-020": ("unexpected_charge", "Unexpected charge on the bill", "mobile bill",
               "An unrecognised charge appears on the bill.",
               ["Review the bill line item and the billing period.",
                "Compare it with the account activity available to the customer.",
                "Route the charge for billing review if it remains unexplained."],
               "The charge remains unexplained after comparison with account activity.",
               "Do not state the cause of a charge without evidence from the bill."),
    "KB-022": ("refund_status", "Checking refund status", "refund",
               "The customer asks where a refund is.",
               ["Verify the refund reference and the original transaction.",
                "Check the available refund status.",
                "Route the case to billing support if the status cannot be confirmed."],
               "The refund status cannot be confirmed.",
               "Do not quote refund timelines; they are not part of this knowledge base."),
    "KB-023": ("plan_change", "Changing plan", "mobile plan",
               "The customer wants to upgrade, downgrade or switch plan.",
               ["Verify the current plan and the requested plan.",
                "Confirm eligibility through the approved plan-change flow.",
                "Submit the change if eligible."],
               "Eligibility cannot be confirmed.",
               "Do not quote plan prices from memory."),
    "KB-024": ("plan_information", "Providing plan information", "mobile plan",
               "The customer asks about available plans.",
               ["Present the currently available plan information from the approved knowledge base.",
                "Ask the customer to select the plan they want to evaluate."],
               "The requested plan information is not available in the approved source.",
               "Do not invent plan features or prices."),
    "KB-025": ("recharge_issue", "Recharge not completed", "recharge plan",
               "A recharge or top-up did not complete, or the balance did not update.",
               ["Verify the recharge transaction status.",
                "Check whether the balance updated.",
                "Route the transaction for review if the recharge remains incomplete."],
               "The recharge remains incomplete after the status check.",
               "Do not promise reversal of a deducted amount."),
    "KB-026": ("sim_activation", "Activating a new SIM", "SIM",
               "A new SIM has not activated.",
               ["Verify the SIM activation request.",
                "Complete the approved activation process.",
                "Restart the device after activation if required."],
               "The SIM does not activate after the approved process.",
               "Do not ask for SIM PUK codes in chat."),
    "KB-027": ("sim_replacement", "SIM or eSIM replacement", "eSIM",
               "The customer needs a replacement SIM or eSIM.",
               ["Verify the account and replacement eligibility through the approved process.",
                "Create the replacement request if eligible."],
               "Eligibility cannot be verified.",
               "Replacement requests always require the approved identity verification."),
    "KB-028": ("sim_not_detected", "SIM not detected by the device", "SIM",
               "The phone reports no SIM or an invalid SIM.",
               ["Power off the device.",
                "Reseat the SIM if appropriate.",
                "Restart the device and test detection again.",
                "Escalate if the SIM remains undetected."],
               "The SIM remains undetected after reseating.",
               "Do not ask the customer to cut or modify the SIM."),
    "KB-029": ("account_security", "Account security concern", "customer account",
               "The customer reports suspicious activity or possible account compromise.",
               ["Do not disclose sensitive account information in chat.",
                "Use the approved account-security process to secure the account.",
                "Escalate suspicious activity for review."],
               "Any suspicious activity is reported.",
               "Treat as critical; never disclose account data before verification."),
    "KB-030": ("service_outage", "Possible service outage", "broadband",
               "The customer believes there is an area outage.",
               ["Check the approved service-status source for the relevant area and service.",
                "Provide only confirmed outage information.",
                "Escalate if no confirmed outage explains the issue."],
               "No confirmed outage explains the issue.",
               "Never speculate about outage causes or restoration times."),
    # --- additional authored ACTIVE articles ----------------------------------------
    "KB-031": ("broadband_disconnects", "Evening broadband drops: time-pattern diagnostic", "broadband",
               "Broadband drops repeatedly at a similar time of day, often in the evening, even after the router has been restarted.",
               ["Record the exact times the drops occur over several days.",
                "Check whether the router/ONT status lights change when the connection drops.",
                "Test whether a wired device drops at the same time as Wi-Fi devices.",
                "If the customer has already restarted the router, do not repeat the restart; move to the line test request.",
                "Request a line test through the approved support process and attach the recorded time pattern."],
               "Drops continue at a repeating time after the router restart, or the customer relies on the service for work.",
               "Do not promise compensation or a fix date."),
    "KB-032": ("billing_dispute", "Duplicate charge review", "mobile bill",
               "The customer reports being charged twice for the same item or period.",
               ["Locate both charges on the bill and note their dates and line-item names.",
                "Check whether the two charges cover the same billing period.",
                "Record the reference of each transaction.",
                "Submit a duplicate-charge dispute through the approved billing process."],
               "Both charges cover the same period and the duplication is confirmed.",
               "Do not promise a refund amount or timeline."),
    "KB-033": ("wifi_not_working", "Wi-Fi coverage and interference checks", "Wi-Fi",
               "Wi-Fi is weak or unstable in parts of the home.",
               ["Check whether the problem occurs near the router as well as far from it.",
                "Restart the router.",
                "Test with a second device in the same location.",
                "Record which rooms and devices are affected for escalation."],
               "Wi-Fi fails close to the router on several devices.",
               "Do not recommend third-party equipment."),
    "KB-034": ("account_security", "Suspected SIM swap or account takeover", "customer account",
               "The customer suddenly lost service and suspects someone changed their SIM, or sees logins they do not recognise.",
               ["Treat the case as critical and do not disclose any account information in chat.",
                "Use the approved account-security process to secure the account.",
                "Escalate immediately to the security team with the time the customer noticed the issue."],
               "Always escalate.",
               "Never reset credentials or move the number without the approved verification."),
    "KB-035": ("roaming_not_working", "Pre-travel and on-arrival roaming checklist", "roaming",
               "Customer is abroad and the phone does not register on a partner network.",
               ["Confirm roaming is enabled on the line before or after travel.",
                "Check that data roaming is switched on in the device settings if data is needed.",
                "Restart the device to trigger network registration.",
                "Record the country and the network name shown on the device for escalation."],
               "Registration still fails after the restart.",
               "Do not quote roaming charges."),
    "KB-036": ("5g_not_available", "5G network mode and SIM compatibility", "5G service",
               "A 5G phone stays on 4G.",
               ["Confirm the device model supports 5G.",
                "Confirm the plan includes 5G service.",
                "Check the preferred network mode includes 5G.",
                "Record the location and network mode shown if 5G is still not available."],
               "5G is not available with a compatible device, plan and network mode.",
               "Do not promise 5G coverage."),
}

# Previously missing articles for the dataset's candidate-only intents, now published (ACTIVE).
KB.update({
    "KB-001": ("mobile_data_not_working", "Mobile data not working: connection checklist", "mobile data",
               "Mobile data is switched on but apps and websites do not load, while calls may still work.",
               ["Verify that mobile data is enabled on the device and that airplane mode is off.",
                "Confirm the device has network service (signal bars shown).",
                "Check that the data balance or plan allowance is available through the approved account view.",
                "Restart the device and retry the data connection.",
                "Collect the device model, location and time of the failure and escalate if data remains unavailable."],
               "Data remains unavailable after restart with network service present.",
               "Do not change APN or network settings that are not listed in this article."),
    "KB-011": ("broadband_no_internet", "Broadband connected but no internet", "broadband",
               "The router shows it is connected but no device can reach the internet.",
               ["Check router/ONT status lights and physical connections.",
                "Restart the router/ONT equipment.",
                "Retry internet access from a second device.",
                "Escalate with device and status-light details if service remains unavailable."],
               "Service remains unavailable on all devices after the restart.",
               "Do not confirm an outage unless it is listed in the approved service-status source."),
    "KB-021": ("payment_failed", "Bill payment failed", "payment",
               "A bill payment was declined or did not complete.",
               ["Verify the payment status through the approved billing view.",
                "Check whether any amount was deducted for the failed attempt.",
                "Retry only through the approved payment flow if appropriate.",
                "Route the case to payment support if the transaction remains unsuccessful."],
               "The transaction remains unsuccessful or an amount was deducted without the bill being paid.",
               "Never ask for full card numbers or security codes in chat."),
})

DRAFT_KB = {
    "KB-042": ("sim_replacement", "Moving an eSIM to a new phone (draft - pending review)", "eSIM",
               "The customer bought a new phone and wants to move their eSIM.",
               ["Verify the account through the approved identity process.", "Issue a new eSIM profile for the new device.",
                "Ask the customer to install the profile and restart the phone."],
               "The new profile does not install.", "Draft: not yet approved by a reviewer."),
}

# General guidance for issues with no specific article. Retrieved as a clearly labelled
# fallback candidate so unseen issues still receive the best-suitable cited guidance.
GENERAL_KB = {
    "KB-037": ("Mobile", "General checklist: a phone feature or setting is not working", "mobile network",
               "A phone feature such as voicemail, visual voicemail, Wi-Fi calling, hotspot, satellite or emergency messaging, or caller ID is missing, greyed out or not working, and no specific article matches.",
               ["Confirm the device model and software version support the feature.",
                "Check that the feature is switched on in the device settings.",
                "Confirm the customer's plan includes the feature using the approved plan information.",
                "Restart the device and test the feature again.",
                "Record the device model, software version and any message shown, then escalate if the feature still does not work."],
               "The feature still fails on a supported device with the plan confirmed.",
               "General guidance only, not a confirmed fix for this specific issue. Do not promise feature availability."),
    "KB-038": ("Internet", "General checklist: a home internet or router feature is not working", "router",
               "A home internet, router or connected-home feature (for example a filter, a smart device, a TV box or a mesh unit) does not work and no specific article matches.",
               ["Confirm whether the problem affects one device or every device on the home network.",
                "Restart the router/ONT and the affected device.",
                "Check the feature's setting in the router or self-care account if one is provided.",
                "Record the device type, the time of the failure and any message shown, then escalate if it continues."],
               "The feature still fails after the restart and settings check.",
               "General guidance only, not a confirmed fix. Do not recommend third-party equipment."),
    "KB-039": ("Calls", "General checklist: a calling or messaging feature is not working", "voice service",
               "A calling or messaging feature (for example call forwarding, conference numbers, international SMS or spam filtering) behaves unexpectedly and no specific article matches.",
               ["Confirm whether the issue affects incoming, outgoing or both directions.",
                "Test with a different number or destination to see whether the issue is specific.",
                "Restart the device and test again.",
                "Record the numbers involved (masked), the times and any message heard, then escalate."],
               "The feature still fails after the test calls.",
               "General guidance only, not a confirmed fix. Never read out or store full customer numbers."),
    "KB-040": ("SIM", "General checklist: SIM, eSIM or connected device problem", "SIM",
               "A SIM, eSIM, smartwatch, tablet, car or vehicle connectivity module, or other connected device line does not work as expected and no specific article matches.",
               ["Confirm which device and which line or profile are affected.",
                "Check that the line or eSIM profile is shown as active for the device.",
                "Restart both the device and any paired phone.",
                "Record the device model, the profile status and any message shown, then escalate if it remains unresolved."],
               "The line or profile is active but the device still cannot use it.",
               "General guidance only. eSIM or SIM changes always require the approved identity verification."),
    "KB-041": ("Billing", "General checklist: billing, payment or account enquiry", "mobile bill",
               "A billing, payment, balance or account question does not match a specific article.",
               ["Identify the bill, transaction or account item the customer is asking about.",
                "Review the item through the approved billing or account view.",
                "Explain only what the approved view shows.",
                "Route the case to billing or account support if the item cannot be explained."],
               "The item cannot be explained from the approved view.",
               "General guidance only. Do not quote prices, credits, refunds or timelines."),
}

CANDIDATES = [
    ("Wi-Fi calling stopped connecting on my phone, calls only work on mobile signal now.", "Calls"),
    ("My Wi-Fi calling toggle is greyed out after the latest phone update.", "Calls"),
    ("Wi-Fi calling says not available at home even though my Wi-Fi itself works fine.", "Calls"),
    ("Wi-Fi calling fails indoors where the mobile signal is weak, the call never connects.", "Calls"),
    ("My smartwatch eSIM stopped sharing my phone number and calls do not ring on the watch.", "SIM"),
    ("The cellular plan on my smartwatch shows no service after pairing with my phone.", "SIM"),
    ("My watch eSIM line cannot receive calls when my phone is switched off.", "SIM"),
    ("Number sharing on my smartwatch failed during setup of the watch eSIM.", "SIM"),
    ("Caller ID shows a different name to the people I call.", "Calls"),
    ("The data usage counter in the app shows usage on days I was offline.", "Mobile"),
    ("Hotspot tethering is blocked on my plan even though I can browse normally.", "Mobile"),
    ("SMS to one specific country never gets delivered.", "SMS"),
]

EVAL_UNKNOWN = [
    "Visual voicemail transcription stopped working after the carrier settings update.",
    "My voicemail greeting resets to the default every week.",
    "Caller ID shows the wrong name when I call people.",
    "My smartwatch cellular line will not pair with my number.",
    "Hotspot tethering is blocked even though browsing works.",
    "The satellite emergency texting feature is not available on my phone.",
    "My number porting request from another operator is stuck.",
    "The parental control filter blocks school websites.",
    "My car's built-in connectivity module lost its connection after the update.",
    "My conference bridge number gives a busy tone.",
    "The spam call filter is blocking calls from my doctor.",
    "My e-reader cannot download books over the cellular connection.",
    "The data usage counter shows usage while I was offline.",
    "My landline voicemail PIN is not accepted.",
    "Call forwarding to my office number stopped working.",
    "My tablet's eSIM QR code says it was already used.",
    "International SMS to one country never delivers.",
    "The app widget shows the wrong remaining balance graphic.",
    "Video calls on a messaging app freeze but voice calls are fine.",
    "My kids' smartwatch location sharing stopped updating.",
]

TICKET_COLUMNS = [
    "record_id", "ticket_id", "customer_id", "dataset_split", "customer_complaint", "category", "intent", "product",
    "severity", "sentiment", "language", "interaction_mode", "channel", "entities_json", "conversation_context",
    "previous_troubleshooting", "retrieval_text", "resolution", "resolution_attempt", "resolution_status",
    "evidence_status", "evidence_score", "citation_source_id", "citation_type", "customer_feedback",
    "human_verification_status", "knowledge_state", "emerging_class_signal", "escalation_required", "created_at",
    "source", "source_type",
]

# Hand-authored demo tickets: (intent, complaint, resolution, kb, severity, sentiment, troubleshooting, time_ref)
AUTHORED = [
    ("broadband_disconnects", "Customer reported recurring broadband disconnections during evening hours around 8 PM; router already restarted twice.",
     "Recorded the evening drop pattern, confirmed the ONT status light changed during drops, skipped a repeat restart and requested a line test with the time pattern attached.", "KB-031", "high", "frustrated", "Router restarted twice", "every evening"),
    ("broadband_disconnects", "Broadband cuts out every night between 8 and 9 PM, customer works from home and needs a stable line.",
     "Collected the time pattern over three days, checked router/ONT indicators during a drop and escalated for a line test.", "KB-031", "high", "urgent", "Router restarted", "every night"),
    ("broadband_disconnects", "Fibre connection drops several times a day and reconnects after a minute.",
     "Checked router/ONT status, restarted the equipment, observed further drops and recorded the time pattern for escalation.", "KB-010", "medium", "negative", "Not stated", "several times a day"),
    ("broadband_slow", "Broadband becomes very slow every evening, video calls freeze.",
     "Restarted the router/ONT, compared speeds on wired and Wi-Fi devices and recorded the evening time pattern.", "KB-009", "medium", "frustrated", "Not stated", "every evening"),
    ("broadband_slow", "Home internet speed is slow only on the laptop, the phone is fine.",
     "Compared performance across devices, identified the issue was limited to one device and recorded the connection details.", "KB-009", "low", "neutral", "Not stated", "today"),
    ("wifi_not_working", "Wi-Fi does not reach the upstairs bedroom and keeps disconnecting there.",
     "Checked coverage near and far from the router, restarted the router and recorded affected rooms for escalation.", "KB-033", "medium", "negative", "Not stated", "daily"),
    ("wifi_not_working", "None of the devices can see the home Wi-Fi network after a power cut.",
     "Confirmed Wi-Fi enabled on devices, restarted the router and verified that all devices could reconnect.", "KB-012", "high", "urgent", "Not stated", "since this morning"),
    ("router_restart_issue", "Customer restarted the router but the connection problem remains, router shows a red light.",
     "Confirmed the restart completed, checked physical links and escalated with the red status indicator.", "KB-013", "high", "frustrated", "Router restarted", "today"),
    ("mobile_data_slow", "Mobile data is very slow in the city centre but fine at home.",
     "Checked signal availability by location, restarted the device and collected location details.", "KB-002", "medium", "negative", "Not stated", "daily"),
    ("no_signal", "Phone shows no service inside the office building.",
     "Restarted the device, confirmed the SIM was seated and escalated with location details when no signal persisted.", "KB-005", "high", "frustrated", "Restart attempted", "every weekday"),
    ("5g_not_available", "New 5G phone only ever shows 4G.",
     "Confirmed device and plan support 5G, corrected the preferred network mode and recorded the observed mode.", "KB-036", "medium", "neutral", "Not stated", "since purchase"),
    ("call_drops", "Calls drop after about one minute when driving to work.",
     "Checked signal availability along the route, restarted the device and recorded time and frequency of the drops.", "KB-003", "medium", "frustrated", "Restart attempted", "every morning"),
    ("call_quality", "Callers say my voice sounds robotic and breaks up.",
     "Checked signal during calls, restarted the device and recorded that only outgoing audio was affected.", "KB-004", "medium", "negative", "Not stated", "this week"),
    ("sms_not_received", "Bank OTP messages are not arriving on my phone.",
     "Restarted the device, verified network service and sent a test message; recorded that incoming SMS was affected.", "KB-006", "high", "urgent", "Not stated", "today"),
    ("sim_not_detected", "Phone says no SIM card after I dropped it.",
     "Powered off, reseated the SIM, restarted and tested detection; escalated when the SIM was still not detected.", "KB-028", "high", "frustrated", "SIM reseated", "since yesterday"),
    ("sim_activation", "New SIM still shows no service two hours after insertion.",
     "Verified the activation request, completed the approved activation process and restarted the device.", "KB-026", "medium", "neutral", "Not stated", "today"),
    ("sim_replacement", "My SIM card is damaged and I need a replacement.",
     "Verified account and replacement eligibility through the approved process and created the replacement request.", "KB-027", "medium", "neutral", "Not stated", "today"),
    ("roaming_not_working", "No mobile service since landing abroad, roaming should be on.",
     "Confirmed roaming enabled, switched on data roaming, restarted the device and recorded the network name shown.", "KB-035", "high", "urgent", "Restart attempted", "since landing"),
    ("billing_dispute", "I was charged twice for the same month on my mobile bill.",
     "Located both charges, confirmed they covered the same billing period, recorded both references and submitted a duplicate-charge dispute.", "KB-032", "medium", "frustrated", "Not stated", "this month"),
    ("billing_dispute", "The invoice total is higher than my plan amount and I want to dispute it.",
     "Reviewed the bill details, identified the disputed line item, recorded the period and reason, and submitted the dispute.", "KB-019", "medium", "negative", "Not stated", "this month"),
    ("unexpected_charge", "There is a charge called 'value added service' that I do not recognise.",
     "Reviewed the line item and billing period, compared with account activity and routed the charge for billing review.", "KB-020", "medium", "negative", "Not stated", "last bill"),
    ("refund_status", "Customer asked about the status of a refund for a cancelled order.",
     "Verified the refund reference and original transaction, checked the refund status and routed to billing support.", "KB-022", "low", "neutral", "Not stated", "last week"),
    ("recharge_issue", "Recharge was deducted from my bank but the balance did not update.",
     "Verified the recharge transaction status, confirmed the balance did not update and routed the transaction for review.", "KB-025", "high", "frustrated", "Not stated", "today"),
    ("plan_change", "Customer wants to move to a plan with more data.",
     "Verified the current and requested plan, confirmed eligibility through the plan-change flow and submitted the change.", "KB-023", "low", "neutral", "Not stated", "today"),
    ("plan_information", "Customer asked which broadband plans are available.",
     "Presented available plan information from the approved knowledge base and asked the customer to select a plan.", "KB-024", "low", "neutral", "Not stated", "today"),
    ("account_login", "App says login failed even with the correct email.",
     "Verified the account identifier, retried login and used the approved account recovery process.", "KB-016", "medium", "negative", "Not stated", "today"),
    ("account_security", "Customer suddenly lost service and received an email about a SIM change they did not request.",
     "Treated as critical, disclosed no account data, secured the account through the security process and escalated immediately.", "KB-034", "critical", "urgent", "Not stated", "today"),
    ("password_reset", "Forgot my password and the reset link has expired.",
     "Used the approved password-reset flow again and completed verification.", "KB-017", "low", "neutral", "Not stated", "today"),
    ("profile_update", "Need to change the email address on my account.",
     "Used the approved profile update flow and verified the saved details.", "KB-018", "low", "neutral", "Not stated", "today"),
    ("service_activation", "Broadband service was installed yesterday but is not active.",
     "Verified activation request status, confirmed the activation step and routed for agent follow-up.", "KB-015", "medium", "negative", "Not stated", "since yesterday"),
    ("new_connection_status", "Customer wants to know when the new fibre installation will happen.",
     "Verified the request reference and checked installation status through the approved process.", "KB-014", "low", "neutral", "Not stated", "this week"),
    ("service_outage", "Customer and neighbours have no internet since the storm.",
     "Checked the approved service-status source, shared only confirmed outage information and escalated as no outage was listed.", "KB-030", "high", "urgent", "Not stated", "since the storm"),
]


def write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)
    print(f"  wrote {path.relative_to(ROOT)} ({len(rows)} rows)")


def kb_content(article_id: str, symptoms: str, steps: list[str], escalate: str, caution: str) -> str:
    """Agent steps, then the same steps worded for customers (one-to-one; see seed_customer_steps.py)."""
    customer = CUSTOMER_STEPS[article_id]
    if len(customer) != len(steps):
        raise ValueError(f"{article_id}: {len(steps)} agent steps but {len(customer)} customer steps")
    lines = [f"Symptoms: {symptoms}", "Resolution steps:"]
    lines += [f"{i}. {s}" for i, s in enumerate(steps, 1)]
    lines += ["Customer steps:"] + [f"{i}. {s}" for i, s in enumerate(customer, 1)]
    lines += [f"Escalate when: {escalate}", f"Caution: {caution}", f"Source note: {SYNTHETIC_NOTE}"]
    return "\n".join(lines)


def build(dataset: Path) -> None:
    DATA.mkdir(exist_ok=True)
    intent_map = {i[0]: i for i in INTENTS}

    write_csv(DATA / "support_categories.csv", ["name", "parent_name", "icon", "description", "sort_order"],
              [[n, p, ic, d, idx] for idx, (n, p, ic, d) in enumerate(SUPPORT_CATEGORIES)])
    write_csv(DATA / "products.csv", ["name", "support_category", "keywords"],
              [[n, c, "|".join(k)] for n, c, k in PRODUCTS])
    write_csv(DATA / "intent_taxonomy.csv",
              ["name", "display_name", "domain_category", "support_category", "default_product", "keywords",
               "example_complaints", "clarifying_question", "description"],
              [[n, d, dc, sc, p, "|".join(k), "|".join(e), q, desc] for n, d, dc, sc, p, k, e, q, desc in INTENTS])

    kb_rows = []
    for status, table in (("ACTIVE", KB), ("DRAFT", DRAFT_KB)):
        for aid, (intent, title, product, symptoms, steps, esc, caution) in sorted(table.items()):
            kb_rows.append([aid, title, kb_content(aid, symptoms, steps, esc, caution), intent_map[intent][3], intent, product,
                            1, status, "synthetic_demo_kb", "2026-01-01T00:00:00", "2026-01-01T00:00:00"])
    for aid, (category, title, product, symptoms, steps, esc, caution) in sorted(GENERAL_KB.items()):
        kb_rows.append([aid, title, kb_content(aid, symptoms, steps, esc, caution), category, "unknown", product,
                        1, "ACTIVE", "synthetic_demo_kb_general", "2026-01-01T00:00:00", "2026-01-01T00:00:00"])
    kb_rows.sort(key=lambda r: r[0])
    write_csv(DATA / "knowledge_base.csv",
              ["article_id", "title", "content", "category", "intent", "product", "version", "status", "source",
               "created_at", "updated_at"], kb_rows)

    write_csv(DATA / "candidate_cases.csv", ["complaint", "category", "source"],
              [[c, cat, "synthetic_demo_authored"] for c, cat in CANDIDATES])
    write_csv(DATA / "eval_unknown_complaints.csv", ["complaint", "expected_status", "source"],
              [[c, "not_known", "synthetic_demo_authored"] for c in EVAL_UNKNOWN])

    rows: list[list] = []
    if dataset.exists():
        rng = random.Random(42)
        by_key: dict[tuple[str, str], list[dict]] = {}
        with dataset.open(newline="", encoding="utf-8") as fh:
            for row in csv.DictReader(fh):
                by_key.setdefault((row["intent"], row["dataset_split"]), []).append(row)
        quota = {"development": 10, "calibration": 2, "held_out_test": 2}
        for (intent, split), group in sorted(by_key.items()):
            for row in rng.sample(group, min(quota.get(split, 0), len(group))):
                rows.append([row[c] for c in TICKET_COLUMNS])
    else:
        print(f"  dataset {dataset} not found - tickets.csv will contain authored demo tickets only")

    for idx, (intent, complaint, resolution, kb, sev, sent, trouble, time_ref) in enumerate(AUTHORED, 1):
        cfg = intent_map[intent]
        product = cfg[4]
        entities = {"product": product, "time_reference": time_ref, "channel": "agent_console"}
        context = f"Product={product}; intent={intent}; issue={cfg[8]}; channel=agent_console; interaction=free_text"
        retrieval = f"{complaint} | {cfg[2]} | {intent} | {product} | {trouble}"
        rows.append([f"DEMO-{idx:06d}", f"DEMO-TKT-{idx:06d}", f"DEMO-CUST-{idx:05d}", "development", complaint, cfg[2],
                     intent, product, sev, sent, "en", "free_text", "agent_console", json.dumps(entities), context, trouble,
                     retrieval, resolution, 1, "resolved", "sufficient", 0.84, kb, "knowledge_base", "solved",
                     "verified_template", "trusted", "none", "yes" if sev == "critical" else "no",
                     f"{(idx % 27) + 1:02d}/0{(idx % 9) + 1}/26", "synthetic_demo_authored", "synthetic_support_ticket"])
    write_csv(DATA / "tickets.csv", TICKET_COLUMNS, rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset", type=Path, default=DATA / "telecom_support_adaptive_60000.csv")
    args = parser.parse_args()
    print(f"Building seed data ({SYNTHETIC_NOTE})")
    build(args.dataset)
