"""Extra example complaints per issue type (used by build_seed_data.py and synced into existing databases).

Customer-style phrasings for the meaning-based classifier. They were written independently of the evaluation sets:
any example too similar to a test question (data/eval_realistic_complaints.csv) or a practice question
(data/tune_realistic_complaints.csv) is rejected by tests/test_answer_quality.py, so the scores stay honest.
"""
EXTRA_EXAMPLES = {
    'broadband_disconnects': [
        'internet keeps cutting out',
        'my connection drops out randomly',
        'broadband disconnects a few times every day',
        'the fibre goes down for a minute then comes back',
        'keep losing internet connection at home',
        'connection keeps resetting throughout the day',
        'wifi router loses connection every few hours',
        'home internet is unstable and keeps going off',
    ],
    'broadband_no_internet': [
        'internet not working at all at home',
        'broadband stopped working completely',
        'router says connected but websites wont open',
        'home internet is dead',
        "can't get online at home since last night",
        'everything is connected but there is no internet access',
        'broadband totally down today',
    ],
    'broadband_slow': [
        'broadband speed has dropped a lot',
        'speed test shows much lower speed than my plan',
        'videos keep loading forever on my home internet',
        'internet is sluggish all the time',
        'downloads at home take ages',
        'fibre is much slower than it used to be',
        'slow wifi speeds at home',
    ],
    'wifi_not_working': [
        "devices won't join the home wifi",
        'wifi is not working in some rooms',
        "my tv can't connect to wifi",
        'wifi password not accepted',
        'home wifi network keeps disappearing',
        'wifi signal is very weak upstairs',
        'cannot see my wifi name in the list',
    ],
    'router_restart_issue': [
        'switched the router off and back on, same issue',
        'the router keeps restarting itself',
        'reset the router but the problem is still there',
        'router stuck restarting over and over',
        'unplugged the router and plugged it back, no change',
    ],
    'mobile_data_not_working': [
        'mobile data stopped working',
        'no internet on my phone without wifi',
        'my phone has signal but no data',
        'cellular data not working since this morning',
        "can't use the internet on my phone away from home",
        'data is switched on but nothing loads',
    ],
    'mobile_data_slow': [
        '4g speed is terrible',
        'data on my phone is really slow today',
        'pages load very slowly on mobile data',
        'phone internet speed dropped',
        'my 5g data feels slow',
        'streaming on mobile data keeps buffering',
        "slow data when I'm outside",
    ],
    'no_signal': [
        'phone shows emergency calls only',
        'lost network signal on my phone',
        'no network on my mobile',
        'signal disappears in my house',
        'there is no mobile signal where I live',
        'my phone lost all reception',
    ],
    '5g_not_available': [
        '5g not working on my phone',
        'phone only connects to 4g not 5g',
        '5g option missing in settings',
        "can't connect to 5g network",
        'my 5g phone stays on lte',
        '5g signal never appears',
        '5g service unavailable',
    ],
    'call_drops': [
        'my calls end suddenly',
        'call disconnects in the middle of talking',
        'phone calls keep cutting off',
        'calls drop after a few seconds',
        'every call I make gets cut',
        'dropped calls all the time',
        'conversation cuts out and the call ends',
    ],
    'call_quality': [
        'bad call quality',
        'voice is choppy during calls',
        'echo on my phone calls',
        'the other person sounds distorted',
        'call audio keeps breaking',
        'static noise on calls',
        'poor sound quality when calling',
        "callers say they can't hear me clearly",
    ],
    'sms_not_received': [
        'not receiving sms',
        'otp messages not coming',
        "can't receive one time passwords",
        "my phone doesn't get texts",
        'messages from my bank never arrive',
        'sms delayed or missing',
    ],
    'sim_not_detected': [
        'no sim detected',
        'insert sim message keeps showing',
        "my phone doesn't recognise the sim",
        'sim stopped being detected',
        'phone shows no sim',
    ],
    'sim_activation': [
        'new sim not activated',
        'sim card still not active',
        'sim activation pending',
        'my new sim has no service yet',
        'sim not activated after a day',
    ],
    'sim_replacement': [
        'my sim card is broken',
        'lost my phone and sim',
        'replace my sim with an esim',
        'order a new sim',
        'my sim got stolen',
    ],
    'roaming_not_working': [
        'no service while travelling overseas',
        "phone doesn't work in another country",
        "can't use data abroad",
        'international roaming not active',
        'no network on holiday abroad',
    ],
    'billing_dispute': [
        'my bill is incorrect',
        "billed for something i didn't use",
        'wrong amount on my invoice',
        'double charged on my account',
        'the bill amount is wrong',
    ],
    'unexpected_charge': [
        'what is this charge',
        'extra fee on my bill',
        'strange charge on my account',
        "charged for a service i didn't order",
        'unknown charge this month',
        "there's an additional charge i didn't expect",
    ],
    'payment_failed': [
        'payment failed',
        "my bill payment didn't work",
        'card declined when paying my bill',
        "can't pay my bill online",
        'payment error on the app',
        'transaction failed while paying',
        'my payment keeps getting rejected',
        'bill payment not going through',
    ],
    'refund_status': [
        'refund not received yet',
        'when will i get my refund',
        'check my refund status',
        'still no refund',
        'refund taking too long',
        'status of my refund',
        "my money hasn't been refunded",
    ],
    'recharge_issue': [
        'recharge not reflected',
        'top up failed',
        'balance not updated after recharge',
        'recharge done but no balance',
        'credit not added after paying',
        'recharge successful but plan not active',
        'topped up but nothing changed',
    ],
    'plan_change': [
        'change my plan',
        'upgrade my plan',
        'switch to another plan',
        'move to a cheaper plan',
        'downgrade my package',
        'i want a different tariff',
        'change to a plan with more data',
    ],
    'plan_information': [
        'what plans do you offer',
        'show me your plans',
        'plan details please',
        'which plan is best for me',
        'compare your plans',
        'information about your packages',
        'what tariffs are available',
        'list of available plans',
    ],
    'account_login': [
        "can't log in",
        'login not working',
        'app says wrong credentials',
        "can't sign in to the website",
        'account locked after login attempts',
        'cannot access my account',
    ],
    'account_security': [
        'suspicious activity on my account',
        'someone changed my password',
        'unauthorised access to my account',
        'my sim was swapped without permission',
        'fraud on my account',
        'strange login on my account',
        'someone is using my number',
    ],
    'password_reset': [
        "didn't get the password reset email",
        'how to change my password',
        'password reset code not arriving',
        'locked out need new password',
    ],
    'profile_update': [
        'change my email',
        'change my address',
        'update my contact number',
        'edit my profile',
        'my name is wrong on my account',
        'change account details',
        'update personal information',
    ],
    'service_activation': [
        "my service isn't working yet after signing up",
        'activate my service',
        'new service still inactive',
        'service activation taking too long',
        "my order hasn't been activated",
        'service not started yet',
        'when will my service be activated',
    ],
    'new_connection_status': [
        'new fibre order status',
        'has my installation been scheduled',
        'engineer visit for new connection',
        'tracking my new connection request',
        'when is my broadband going live',
    ],
    'service_outage': [
        'is there an outage',
        'service down for everyone near me',
        'outage affecting my area',
        'everyone around me has no service',
        'is there a problem with your network today',
        'area wide internet outage',
    ],
}
